In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from numpy import nan
%run opentable.ipynb


merged_market_path = "/Gdrive/zx/highres/merged/"
tick_path = "/Gdrive/zx/highres/arbmm/factors/"

sids = [
    {"exchange":"okxswap", "sid":0},
    {"exchange":"binanceswap", "sid":1},
    {"exchange":"bybitswap", "sid":2}
]

ks_file = [
    {"exchange":"okxswap", "ttype":"maker", "fee":-0.00005},
    {"exchange":"okxswap", "ttype":"taker", "fee":0.00015},
    {"exchange":"binanceswap", "ttype":"maker", "fee":-0.00005},
    {"exchange":"binanceswap", "ttype":"taker", "fee":0.00015},
    {"exchange":"bybitswap", "ttype":"maker", "fee":-0.0001},
    {"exchange":"bybitswap", "ttype":"taker", "fee":0.00025},
    {"exchange":"binancespot", "ttype":"maker", "fee":-0.00004},
    {"exchange":"binancespot", "ttype":"taker", "fee":0.00018},
    {"exchange":"okxspot", "ttype":"maker", "fee":-0.00005},
    {"exchange":"okxspot", "ttype":"taker", "fee":0.0002},
]

In [2]:
path = merged_market_path+"/APEUSDT_20240213.npy"
nm = np.load(path)

In [3]:
df_nm = pd.DataFrame(nm)
df_nm.columns = ["timestamp","is","sideid","price","amount","tid","sid"]

In [27]:
tdf_nm = df_nm[(df_nm["tid"] == 1) & (df_nm["sid"] == 0)]

In [28]:
tdf_nm

             timestamp   is  sideid  price    amount  tid  sid
113       1.707782e+15  0.0     1.0  1.480  372353.0  1.0  0.0
114       1.707782e+15  0.0     1.0  1.480  369399.0  1.0  0.0
146       1.707782e+15  1.0     1.0  1.478   61551.0  1.0  0.0
147       1.707782e+15  1.0     1.0  1.479  185926.0  1.0  0.0
148       1.707782e+15  1.0     1.0  1.480  362620.0  1.0  0.0
149       1.707782e+15  1.0     1.0  1.481  568426.0  1.0  0.0
150       1.707782e+15  1.0     1.0  1.482  545263.0  1.0  0.0
151       1.707782e+15  1.0     1.0  1.483  418544.0  1.0  0.0
152       1.707782e+15  1.0     1.0  1.484  282150.0  1.0  0.0
153       1.707782e+15  1.0     1.0  1.485  375448.0  1.0  0.0
154       1.707782e+15  1.0     1.0  1.486  300640.0  1.0  0.0
155       1.707782e+15  1.0     1.0  1.487  350484.0  1.0  0.0
156       1.707782e+15  1.0     1.0  1.488  137276.0  1.0  0.0
157       1.707782e+15  1.0     1.0  1.489   53051.0  1.0  0.0
158       1.707782e+15  1.0     1.0  1.490   43653.0  1.0  0.0
159       1.707782e+15  1.0     1.0  1.491   41540.0  1.0  0.0
160       1.707782e+15  1.0     1.0  1.492   34458.0  1.0  0.0
161       1.707782e+15  1.0     1.0  1.493  291811.0  1.0  0.0
162       1.707782e+15  1.0     1.0  1.494   29793.0  1.0  0.0
163       1.707782e+15  1.0     1.0  1.495   73904.0  1.0  0.0
164       1.707782e+15  1.0     1.0  1.496   23042.0  1.0  0.0
165       1.707782e+15  1.0     1.0  1.497   25344.0  1.0  0.0
166       1.707782e+15  1.0     1.0  1.498   60586.0  1.0  0.0
167       1.707782e+15  1.0     1.0  1.499   44880.0  1.0  0.0
168       1.707782e+15  1.0     1.0  1.500  715497.0  1.0  0.0
169       1.707782e+15  1.0     1.0  1.501   30657.0  1.0  0.0
170       1.707782e+15  1.0     1.0  1.502   41774.0  1.0  0.0
171       1.707782e+15  1.0     1.0  1.503   24282.0  1.0  0.0
172       1.707782e+15  1.0     1.0  1.504    9873.0  1.0  0.0
173       1.707782e+15  1.0     1.0  1.505   11767.0  1.0  0.0
...                ...  ...     ...    ...       ...  ...  ...
19694327  1.707869e+15  0.0     1.0  1.531  428803.0  1.0  0.0
19694364  1.707869e+15  0.0     1.0  1.528   38888.0  1.0  0.0
19694365  1.707869e+15  0.0     1.0  1.528   42444.0  1.0  0.0
19694372  1.707869e+15  0.0     0.0  1.527   45474.0  1.0  0.0
19694417  1.707869e+15  0.0     1.0  1.528   38888.0  1.0  0.0
19694421  1.707869e+15  0.0     1.0  1.528   42451.0  1.0  0.0
19694424  1.707869e+15  0.0     1.0  1.528   41037.0  1.0  0.0
19694426  1.707869e+15  0.0     1.0  1.528   42459.0  1.0  0.0
19694436  1.707869e+15  0.0     1.0  1.528   42456.0  1.0  0.0
19694459  1.707869e+15  0.0     1.0  1.528   30456.0  1.0  0.0
19694460  1.707869e+15  0.0     0.0  1.527   35474.0  1.0  0.0
19694473  1.707869e+15  0.0     0.0  1.527   36004.0  1.0  0.0
19694474  1.707869e+15  0.0     0.0  1.526  157753.0  1.0  0.0
19694476  1.707869e+15  0.0     1.0  1.529  147504.0  1.0  0.0
19694477  1.707869e+15  0.0     1.0  1.533  316249.0  1.0  0.0
19694478  1.707869e+15  0.0     1.0  1.537  179104.0  1.0  0.0
19694479  1.707869e+15  0.0     1.0  1.545   34408.0  1.0  0.0
19694480  1.707869e+15  0.0     0.0  1.525  248920.0  1.0  0.0
19694481  1.707869e+15  0.0     0.0  1.522  404860.0  1.0  0.0
19694482  1.707869e+15  0.0     0.0  1.517   55640.0  1.0  0.0
19694483  1.707869e+15  0.0     0.0  1.510   43491.0  1.0  0.0
19694488  1.707869e+15  0.0     1.0  1.566   13205.0  1.0  0.0
19694489  1.707869e+15  0.0     1.0  1.799     953.0  1.0  0.0
19694490  1.707869e+15  0.0     0.0  1.526  158862.0  1.0  0.0
19694491  1.707869e+15  0.0     0.0  1.521  296574.0  1.0  0.0
19694506  1.707869e+15  0.0     1.0  1.528   30256.0  1.0  0.0
19694515  1.707869e+15  0.0     1.0  1.528   30474.0  1.0  0.0
19694545  1.707869e+15  0.0     0.0  1.527   35365.0  1.0  0.0
19694548  1.707869e+15  0.0     1.0  1.528   29052.0  1.0  0.0
19694549  1.707869e+15  0.0     1.0  1.528   30491.0  1.0  0.0

[3535042 rows x 7 columns]

In [15]:
tdf_nm.groupby("sid").sum()["amount"]

sid
0.0    203795126.0
1.0     61741314.0
2.0     16816919.6
Name: amount, dtype: float64

In [25]:
#1s 
kpath = "/Gdrive/5exchange_apt_ape_routine1s_l2_trade_7day/routine_1s/20240213/okex-swap/20240213_APE-USDT-SWAP.csv"
# kpath = "/Gdrive/5exchange_apt_ape_routine1s_l2_trade_7day/routine_1s/20240213/binance-futures/20240213_APEUSDT.csv"
# kpath = "/Gdrive/5exchange_apt_ape_routine1s_l2_trade_7day/routine_1s/20240213/bybit/20240213_APEUSDT.csv"

nk = pd.read_csv(kpath)

In [26]:
nk["amount"] = nk["buy_amount"] + nk["sell_amount"]
nk["amount"].sum()

195142511

In [17]:
nk

,m,timestamp,bid_price,ask_price,buy_high,buy_low,sell_high,sell_low,ind,mid_avg_price,interval,buy_amount,sell_amount,buy_count,sell_count,lastts,amount
0,20240213,1707857662000000,1.518,1.519,NaN,NaN,NaN,NaN,2.100000e-07,1.5185,1,0,0,0,0,1707857661970000,0
1,20240213,1707857661000000,1.518,1.519,NaN,NaN,NaN,NaN,1.955556e-07,1.5185,1,0,0,0,0,1707857660460000,0
2,20240213,1707857660000000,1.518,1.519,NaN,NaN,NaN,NaN,1.788889e-07,1.5185,1,0,0,0,0,1707857659830000,0
3,20240213,1707857659000000,1.518,1.519,NaN,NaN,NaN,NaN,1.600000e-07,1.5185,1,0,0,0,0,1707857658610000,0
4,20240213,1707857658000000,1.518,1.519,NaN,NaN,NaN,NaN,1.388889e-07,1.5185,1,0,0,0,0,1707857657210000,0
5,20240213,1707857657000000,1.518,1.519,1.519,1.519,NaN,NaN,1.155556e-07,1.5185,1,2000,0,1,0,1707857656560000,2000
6,20240213,1707857656000000,1.518,1.519,NaN,NaN,NaN,NaN,9.000000e-08,1.5185,1,0,0,0,0,1707857655980000,0
7,20240213,1707857655000000,1.518,1.519,1.519,1.519,NaN,NaN,6.222222e-08,1.5185,1,3,0,1,0,1707857654380000,3
8,20240213,1707857654000000,1.518,1.519,1.519,1.519,NaN,NaN,3.222222e-08,1.5185,1,20,0,1,0,1707857653620000,20
9,20240213,1707857653000000,1.518,1.519,1.518,1.518,NaN,NaN,0.000000e+00,1.5185,1,8793,0,6,0,1707857652840000,8793
10,20240213,1707857652000000,1.517,1.518,NaN,NaN,NaN,NaN,0.000000e+00,1.5175,1,0,0,0,0,1707857651800000,0
11,20240213,1707857651000000,1.517,1.518,NaN,NaN,NaN,NaN,0.000000e+00,1.5175,1,0,0,0,0,1707857650370000,0
12,20240213,1707857650000000,1.517,1.518,1.518,1.518,NaN,NaN,0.000000e+00,1.5175,1,18,0,1,0,1707857649940000,18
13,20240213,1707857649000000,1.517,1.518,1.518,1.518,NaN,NaN,0.000000e+00,1.5175,1,20,0,1,0,1707857648510000,20
14,20240213,1707857648000000,1.517,1.518,NaN,NaN,NaN,NaN,0.000000e+00,1.5175,1,0,0,0,0,1707857647760000,0
15,20240213,1707857647000000,1.517,1.518,1.518,1.518,NaN,NaN,0.000000e+00,1.5175,1,9,0,1,0,1707857646710000,9
16,20240213,1707857646000000,1.517,1.518,1.518,1.518,NaN,NaN,0.000000e+00,1.5175,1,3179,0,10,0,1707857645980000,3179
17,20240213,1707857645000000,1.517,1.518,NaN,NaN,NaN,NaN,0.000000e+00,1.5175,1,0,0,0,0,1707857644760000,0
18,20240213,1707857644000000,1.517,1.518,NaN,NaN,1.517,1.517,0.000000e+00,1.5175,1,0,1,0,1,1707857643890000,1
19,20240213,1707857643000000,1.517,1.518,NaN,NaN,NaN,NaN,0.000000e+00,1.5175,1,0,0,0,0,1707857642800000,0
20,20240213,1707857642000000,1.517,1.518,NaN,NaN,1.517,1.517,0.000000e+00,1.5175,1,0,503,0,2,1707857641520000,503
21,20240213,1707857641000000,1.517,1.518,NaN,NaN,NaN,NaN,0.000000e+00,1.5175,1,0,0,0,0,1707857640540000,0
22,20240213,1707857640000000,1.517,1.518,NaN,NaN,NaN,NaN,0.000000e+00,1.5175,1,0,0,0,0,1707857639840000,0
23,20240213,1707857639000000,1.517,1.518,NaN,NaN,NaN,NaN,0.000000e+00,1.5175,1,0,0,0,0,1707857638390000,0
24,20240213,1707857638000000,1.517,1.518,NaN,NaN,NaN,NaN,0.000000e+00,1.5175,1,0,0,0,0,1707857637250000,0
25,20240213,1707857637000000,1.517,1.518,NaN,NaN,NaN,NaN,0.000000e+00,1.5175,1,0,0,0,0,1707857636870000,0
26,20240213,1707857636000000,1.517,1.518,NaN,NaN,NaN,NaN,3.222222e-08,1.5175,1,0,0,0,0,1707857635860000,0
27,20240213,1707857635000000,1.517,1.518,NaN,NaN,NaN,NaN,6.222222e-08,1.5175,1,0,0,0,0,1707857634250000,0
28,20240213,1707857634000000,1.517,1.518,NaN,NaN,NaN,NaN,9.000000e-08,1.5175,1,0,0,0,0,1707857633720000,0
29,20240213,1707857633000000,1.517,1.518,NaN,NaN,1.517,1.517,1.155556e-07,1.5175,1,0,199,0,1,1707857632320000,199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86369,20240213,1707857692000000,1.519,1.520,NaN,NaN,NaN,NaN,1.566667e-07,1.5195,1,0,0,0,0,1707857691980000,0
86370,20240213,1707857691000000,1.519,1.520,NaN,NaN,NaN,NaN,1.955556e-07,1.5195,1,0,0,0,0,1707857690890000,0
86371,20240213,1707857690000000,1.519,1.520,NaN,NaN,NaN,NaN,2.322222e-07,1.5195,1,0,0,0,0,1707857689400000,0
86372,20240213,1707857689000000,1.519,1.520,NaN,NaN,NaN,NaN,2.666667e-07,1.5195,1,0,0,0,0,1707857688410000,0
86373,20240213,1707857688000000,1.519,1.520,NaN,NaN,NaN,NaN,2.988889e-07,1.5195,1,0,0,0,0,1707857687200000,0
86374,20240213,1707857687000000,1.519,1.520,NaN,NaN,NaN,NaN,3.288889e-07,1.5195,1,0,0,0,0,1707857686930000,0
86375,20240213,1707857686000000,1.519,1.520,NaN,NaN,NaN,NaN,3.566667e-07,1.5195,1,0,0,0,0,1707857685750000,0
86376,20240213,1707857685000000,1.519,1.520,NaN,NaN,NaN,NaN,3.822222e-07,1.5195,1,0,0,0,0,1707857684770000,0
86377,20240213,1707857684000000,1.519,1.520,NaN,NaN,NaN,NaN,4.055556e-07,1.5195,1,0,0,0,0,1707857683650000,0
86378,20240213,1707857683000000,1.519,1.520,1.520,1.520,NaN,NaN,4.266667e-07,1.5195,1,1798,0,2,0,1707857682380000,1798
86379,20240213,1707857682000000,1.519,1.520,NaN,NaN,1.520,1.520,5.288889e-07,1.5195,1,0,52519,0,10,1707857681570000,52519
86380,20240213,1707857681000000,1.520,1.521,1.521,1.521,NaN,NaN,5.655556e-07,1.5205,1,3555,0,2,0,1707857680970000,3555
86381,20240213,1707857680000000,1.520,1.521,NaN,NaN,NaN,NaN,5.822222e-07,1.5205,1,0,0,0,0,1707857679860000,0
86382,20240213,1707857679000000,1.520,1.521,NaN,NaN,NaN,NaN,5.788889e-07,1.5205,1,0,0,0,0,1707857678600000,0
86383,20240213,1707857678000000,1.520,1.521,1.520,1.520,NaN,NaN,5.555556e-07,1.5205,1,77710,0,17,0,1707857677990000,77710
86384,20240213,1707857677000000,1.519,1.520,NaN,NaN,NaN,NaN,5.955556e-07,1.5195,1,0,0,0,0,1707857676970000,0
86385,20240213,1707857676000000,1.519,1.520,NaN,NaN,NaN,NaN,6.266667e-07,1.5195,1,0,0,0,0,1707857675940000,0
86386,20240213,1707857675000000,1.519,1.520,NaN,NaN,NaN,NaN,6.488889e-07,1.5195,1,0,0,0,0,1707857674910000,0
86387,20240213,1707857674000000,1.519,1.520,NaN,NaN,NaN,NaN,6.622222e-07,1.5195,1,0,0,0,0,1707857673510000,0
86388,20240213,1707857673000000,1.519,1.520,NaN,NaN,NaN,NaN,6.666667e-07,1.5195,1,0,0,0,0,1707857672530000,0
86389,20240213,1707857672000000,1.519,1.520,NaN,NaN,NaN,NaN,6.622222e-07,1.5195,1,0,0,0,0,1707857671460000,0
86390,20240213,1707857671000000,1.519,1.520,NaN,NaN,NaN,NaN,6.488889e-07,1.5195,1,0,0,0,0,1707857670570000,0
86391,20240213,1707857670000000,1.519,1.520,NaN,NaN,1.519,1.519,6.266667e-07,1.5195,1,0,26,0,1,1707857669800000,26
86392,20240213,1707857669000000,1.519,1.520,NaN,NaN,NaN,NaN,5.955556e-07,1.5195,1,0,0,0,0,1707857668980000,0
86393,20240213,1707857668000000,1.519,1.520,NaN,NaN,NaN,NaN,5.555556e-07,1.5195,1,0,0,0,0,1707857667810000,0
86394,20240213,1707857667000000,1.519,1.520,NaN,NaN,NaN,NaN,5.066667e-07,1.5195,1,0,0,0,0,1707857666210000,0
86395,20240213,1707857666000000,1.519,1.520,NaN,NaN,NaN,NaN,4.488889e-07,1.5195,1,0,0,0,0,1707857665890000,0
86396,20240213,1707857665000000,1.519,1.520,NaN,NaN,NaN,NaN,3.822222e-07,1.5195,1,0,0,0,0,1707857664820000,0
86397,20240213,1707857664000000,1.519,1.520,NaN,NaN,NaN,NaN,3.066667e-07,1.5195,1,0,0,0,0,1707857663730000,0
86398,20240213,1707857663000000,1.519,1.520,1.519,1.519,NaN,NaN,2.222222e-07,1.5195,1,3431,0,4,0,1707857662950000,3431